project:
  type: website
  output-dir: _site
  resources: 
    - assets

website:
  title: "Mirian Lima"
  site-url: https://mirianlima.github.io/
  description: "Policy Researcher and data expert, applying economic development data science in favor of evidence-based public policy making."
  favicon: assets/fav.png
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    title: "MIRIAN<span class='icon-line'></span>LIMA"
    tools:
    - icon: github
      href: https://github.com/mirianlima/mirianlima.github.io
    right:
    - text: "Blog"
      aria-label: "Blog"
      href: blog/index.qmd
        # aria-label: "About Me"
        # href: about/index.qmd
        
  page-footer:  
    center: >-
     &#169; 2024 Mirian Lima &#8729; 
     <a href="https://github.com/mirianlima" class="connect" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
     <a href="https://www.linkedin.com/in/mspencerlima" class="connect" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
     &#8729;
     Made with [Quarto](https://quarto.org)

format:
  html:
    theme: [cosmo, assets/main.scss]
    toc: true
    pagetitle: "{{< meta title >}} | Mirian Lima"
    lightbox: true
    code-link: true
    link-external-icon: true
    link-external-newwindow: true

execute: 
  freeze: auto
